### ISSUE TITLE
mac support

### ISSUE THREAD

**Issue by kvonspiczak** [nklbdev/godot-4-aseprite-importers#1]
should this work on mac?
i'm running mac os ventura 13.4.1. i set the executable path to `/Applications/Aseprite.app/Contents/MacOS/aseprite` but I guess its not implemented yet, since it expects a .exe path?

anyways nice work guys!

**Comment by nklbdev** [comment]
Hello, @kvonspiczak! You can try to paste yout path in this settings field via Cmd+V.
Please, tell me what happends in this case on mac (with screenshot), and I'll try to fix it )))

**Comment by nklbdev** [comment]
I'm currently finishing up the development of [a bundle of import plugins](https://github.com/nklbdev/godot-4-importality) for several graphical applications: Aseprite, Pencil2D, Krita, Piskel, Pixelorama and GraphicsGale.

It is already somewhat functional, but requires fine-tuning and documentation.

The new bundle will be the successor to this plugin. I will not develop this plugin (except for hotfixes). I will focus entirely on the development of a new bundle.

**Comment by kvonspiczak** [comment]
I managed to use the file selector button and simply choose „all files“ instead of „.exe“ which was preselected in the file selection window. 

Nothing happens when I reimport a simple aseprite file as sprite though

**Comment by nklbdev** [comment]
Try running Godot from a terminal and show me a listing of its output

**Comment by kvonspiczak** [comment]
i managed to open it via CLI and cannot reproduce it anymore. i guess this issue can be closed then.
probably did some mistake yesterday (was late and tired :D )
thanks for your help though!

**Comment by nklbdev** [comment]
@kvonspiczak, were you able to import your *.aseprite files into Godot animations?

**Comment by kvonspiczak** [comment]
I don’t have animations yet. I was just trying out the .aseprite to sprite way. It works now yes!
